### ISSUE TITLE
Crystal tracking toggle shows Shayzien with the wrong number of pieces

### ISSUE THREAD

**Issue by Jin-Jiyunsun** [Fiskmans/rl_partial_sets#1]
https://github.com/Fiskmans/rl_partial_sets/assets/37377657/0b2be976-4320-44f4-936c-adbe66b25d75

see video above

**Comment by Fiskmans** [comment]
Thanks for the report, 
It's the correct number of pieces since the slayer helm counts
I'll have a look as to why It's toggled by the crystal setting

**Comment by Fiskmans** [comment]
fixed in #53ae807da2e64f01311731d5c5a3853969f851a9
